version: "3.7"
services:
  ednevnik:
    build: .
    container_name: ednevnik
    image: ednevnik:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 80:8080
    networks:
      - rest-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:5.7
    networks:
      - rest-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=ednevnik
      - MYSQL_USER=user
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
networks:
  rest-network:
    driver: bridge
volumes:
  mysql-data:
  java-data: